---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    name: zk-cluster
    type: nfs
spec:
  storageClassName: manual
  nfs:
    path: /test/pgdb
    server: 192.168.65.14
  accessModes:
  - "ReadWriteOnce"
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
